### ISSUE TITLE
benchmarking code availability

### ISSUE THREAD

**Issue by minhduchoang301** [mir-pucrs/smartix-rl#15]
Hi, I wonder if there are codes that you use for the benchmarking in the paper (query-per-hour metric and index size) ?

**Comment by meneguzzi** [comment]
@gabrielplicks , did we not get this from TPC website?

**Comment by minhduchoang301** [comment]
> @gabrielplicks , did we not get this from TPC website?

Can you please clarify? In the paper, it seems that you executed your own experiments 12 times, removed the highest and lowest and get the average

**Comment by gabrielplicks** [comment]
Hi @minhduchoang301, sorry for the delay. I implemented a script to run the TPC-H benchmark myself. I followed the instructions from the [documentation in the TPC website](http://www.tpc.org/tpc_documents_current_versions/current_specifications5.asp). What you need is to generate the data to populate the database (DBGEN binary file in the TPC-H tools) and then generate the queries (QGEN binary file in the TPC-H tools). Finally, you just need a script that runs the queries following the protocol documented in the TPC-H website and extract the running times in order to compute the metrics (equations for the metrics are also in the documentation).
